DROP TABLE IF EXISTS users;
CREATE TABLE users (
  login    VARCHAR(255) PRIMARY KEY NOT NULL,
  password VARCHAR(255)             NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE    NOT NULL
);
INSERT INTO users VALUES ('user', 'ee11cbb19052e40b07aac0ca060c23ee', FALSE),
  ('admin', '21232f297a57a5a743894a0e4a801fc3', TRUE),
  ('user2', '7e58d63b60197ceb55a1c487989a3720', FALSE),
  ('admin3', '32cacb2f994f6b42183a1300d9a3e8d6', TRUE);

CREATE SEQUENCE IF NOT EXISTS SEQ_BOOKS_TABLE START WITH 21;
DROP TABLE IF EXISTS books;
CREATE TABLE books (
  id             INT DEFAULT (NEXT VALUE FOR SEQ_BOOKS_TABLE) PRIMARY KEY NOT NULL,
  author         VARCHAR(255)                                             NOT NULL,
  title          VARCHAR(255)                                             NOT NULL,
  description    TEXT,
  published_year INT
);
INSERT INTO books VALUES (1, 'Хорстманн Кей С., Корнелл Гари', 'Библиотека профессионала. Java 2. Том 1. Основы.',
                          'Книга адресована, прежде всего, программистам-профессионалам и представляетсобой исчерпывающий справочник и методическое пособие по основам программи-рования на языке Java. Однако это не просто учебник по синтаксису языка. Назначе-ние книги - обучить методам объектно-ориентированного программирования и ре-шения основных проблем в этой области. Работа с книгой не требует опыта програм-мирования на языке C++ и применения методов ООП. Любой программист, работавший с языками Visual Basic, С, Cobol или Pascal, не будет испытывать затруд-нений при работе с ней. Книга содержит многочисленные примеры и советы по про-граммированию, а также разделы, в которых рассматриваются методы тестирования и отладки программ, абстрактные типы данных, базовое объектно-ориентированноепрограммирование, включающее событийно-управляемое программирование. Книгуможно использовать не только как учебник, но и как справочник.',
                          2014),
  (2, 'Хорстманн Кей С., Корнелл Гари',
   'Библиотека профессионала. Java 2. Том 2. Расширенные средства программирования.',
   'Книга предназначена для опытных программистов, которые хотели бы овладеть профессиональными приемами программирования Java-приложений и аплетов: многопоточное программирование, коллекции, работа с сетями и базами данных, распределенное программирование, библиотеки Swing и AWT, технология JavaBeans, вопросы обеспечения безопасности и локализации приложений, использование платформно-зависимого кода и языка XML. Каждая глава посвящена описанию отдельной темы, они практически не связаны друг с другом, поэтому их можно читать в произвольном порядке. Описание всех важных концепций иллюстрируется надежными и практичными, а не примитивными или чрезмерно академичными примерами. Все они сопровождаются многочисленными полезными и уместными комментариями. Как сказал Гради Буч (Grady Booch), авторы "уделили большое внимание деталям этого мощного и выразительного языка без ущерба для концептуальной модели объектно-ориентированного программирования"',
   2014),
  (3, 'Брюс Эккель', 'Философия Java, 4-е издание',
   'Впервые читатель может познакомиться с полной версией этого классического труда, который ранее на русском языке печатался в сокращении. Книга, выдержавшая в оригинале не одно переиздание, за глубокое и поистине философское изложение тонкостей языка Java считается одним из лучших пособий для программистов. Чтобы по-настоящему понять язык Java, необходимо рассматривать его не просто как набор неких команд и операторов, а понять его «философию», подход к решению задач, в сравнении с таковыми в других языках программирования. На этих страницах автор рассказывает об основных проблемах написания кода: в чем их природа и какой подход использует Java в их разрешении. Поэтому обсуждаемые в каждой главе черты языка неразрывно связаны с тем, как они используются для решения определенных задач.',
   2015),
  (4, 'Крис Шефер, Кларенс Хо, Роб Харроп', 'Spring 4 для профессионалов, 4-е издание',
   'Книга представляет собой многолетний бестселлер, который обновлен с целью отражения функциональных средств, предлагаемых последней версией платформы Spring Framework 4. С выходом 4-го издания эта популярная книга безоговорочно считается наиболее исчерпывающим и авторитетным руководством по Spring.
 Вы изучите основы и ключевые темы, связанные с платформой Spring. Авторы поделятся с вами собственным реальным опытом в области удаленной обработки, использования Hibernate и работы с EJB. Помимо основ вы научитесь применять Spring Framework для построения разнообразных уровней или частей корпоративного Java-приложения: транзакций, веб-уровня и уровня презентаций, развертывания и многого другого.
 Многочисленные примеры помогут вам в освоении технологий и приемов, рассмотренных в этой книге, а также в организации их совместной работы.',
   2015),
  (5, 'Дэвид Гери, Кей Хорстманн', 'JavaServer Faces, 3-е издание', 'Книга содержит исчерпывающие сведения по созданию веб-приложений на основе технологии JavaServer Faces (JSF). В ней показано, по какому принципу платформа JSF обеспечивает разделение дизайна страницы и логики приложения и как можно без особых затруднений реализовать веб-приложения, применяя заранее подготовленные компоненты в сочетании с кодом Java. Подробно описано, какое место JSF занимает среди общего набора средств создания приложений Java EE и как расширить возможности JSF, если встроенных средств недостаточно для решения конкретных задач. Программное обеспечение, необходимое для работы с книгой, доступно бесплатно.
В книге приведены многочисленные сценарии, файлы конфигурации, файлы определения ресурсов, веб-страницы и готовые программы, которые подробно описаны, тщательно прокомментированы и составляют основу практически значимых приложений. Код рассматриваемых примеров можно получить с сопровождающего веб-сайта.
Книга дополняет оперативную документацию, содержит все необходимые справочные данные.', 2011),
  (6, 'Тимур Машнин', 'Web-сервисы Java',
   'Рассмотрены основы технологии Web-сервисов в спецификациях первого и второго уровня, реализация технологии Web-сервисов в виде стандартов платформы Java и в таких распространенных Java-стеках Web-сервисов как Metro, СXF и Axis2. Материал книги сопровождается более 70 примерами с подробным анализом исходных кодов. На сайте издательства находятся проекты примеров из книги, а также дополнительные материалы.',
   2012),
  (7, 'Ричард Уорбэртон', 'Лямбда-выражения в Java 8. Функциональное программирование – в массы',
   'Если вы имеете опыт работы с Java SE, то из этой книги узнаете об изменениях в версии Java 8, обусловленных появлением в языке лямбда-выражений. Вашему вниманию будут представлены примеры кода, упражнения и увлекательные объяснения того, как можно использовать эти анонимные функции, чтобы сделать код проще и чище, и как библиотеки помогают в решении прикладных задач.
Лямбда-выражения – относительно простое изменение в языке Java; в первой части книги показано, как правильно ими пользоваться. В последующих главах демонстрируется, как лямбда-выражения позволяют повысить производительность программы за счет распараллеливания, писать более простой конкурентный код и точнее моделировать предметную область, в том числе создавать более качественные предметно-ориентированные языки.
Издание предназначено для программистов разной квалификации, как правило уже работающих с Java, но не имеющих опыта функционального программирования.',
   2014),
  (8, 'Ian F. Darwin',
   'Java Cookbook, Third Edition',
   'From lambda expressions and JavaFX 8 to new support for network programming and mobile development, Java 8 brings a wealth of changes. This cookbook helps you get up to speed right away with hundreds of hands-on recipes across a broad range of Java topics. You’ll learn useful techniques for everything from debugging and data structures to GUI development and functional programming.
Each recipe includes self-contained code solutions that you can freely use, along with a discussion of how and why they work. If you are familiar with Java basics, this cookbook will bolster your knowledge of the language in general and Java 8’s main APIs in particular.',
   2014),
  (9, 'Toby Weston', 'Learn Scala for Java Developers',
   'Scala is a concise, statically typed scripting language that runs on the Java Virtual Machine. It is both a functional programming language and object-oriented language but its emphasis on functional programming sets it apart from Java.
Learn Scala for Java Developers is for Java developers looking to transition to programming Scala. The book will help you translate the Java you already know into Scala and kick-start your productivity.',
   2015),
  (10, 'Herbert Schildt', 'Introducing JavaFX 8 Programming', 'Introducing JavaFX 8 Programming provides a fast-paced, practical introduction to JavaFX, Java’s next-generation GUI programming framework. In this easy-to-read guide, best-selling author Herb Schildt presents the key topics and concepts you’ll need to start developing modern, dynamic JavaFX GUI applications. The book begins with the fundamentals, including the general form of a JavaFX program. You then advance to event handling, controls, images, fonts, layouts, effects, transforms, animations (including 3-D animations), menus, and more. Numerous complete examples are included that put key topics and techniques into action. Designed for Java programmers, the book’s focus is on the JavaFX API and all examples are written entirely in Java. Best of all, the book is written in the clear, crisp, uncompromising style that has made Herb Schildt the choice of millions worldwide.', 2015),
  (11, 'Майкл Фицджеральд', 'Регулярные выражения. Основы',
   'Если вы программист, не имеющий опыта работы с регулярными выражениями, то данная книга — как раз то, что нужно для первого знакомства с ними. Многочисленные примеры, приведенные в книге, не только помогут вам освоить основы регулярных выражений, но и научат применять их для поиска, извлечения и преобразования фрагментов текста посредством их сопоставления с определенными символами, словами и шаблонами.
Регулярные выражения эффективно применяются во многих областях программирования. Они доступны в утилитах UNIX и таких языках программирования, как Perl, Java, JavaScript и С#. Прочитав книгу, вы будете знать синтаксис наиболее распространенных диалектов регулярных выражений и понимать, в каких случаях они смогут обеспечить вам значительную экономию времени.',
   2015),
  (12, 'Cay S. Horstmann',
   'Core Java for the Impatient',
   'he release of Java SE 8 introduced significant enhancements that impact the Core Java technologies and APIs at the heart of the Java platform. Many old Java idioms are no longer required and new features like lambda expressions will increase programmer productivity, but navigating these changes can be challenging.
Core Java® for the Impatient is a complete but concise guide to Java SE 8. Written by Cay Horstmann—the author of Java SE 8 for the Really Impatient and Core Java™, the classic, two-volume introduction to the Java language—this indispensable new tutorial offers a faster, easier pathway for learning the language and libraries. Given the size of the language and the scope of the new features introduced in Java SE 8, there’s plenty of material to cover, but it’s presented in small chunks organized for quick access and easy understanding.
If you’re an experienced programmer, Horstmann’s practical insights and sample code will help you quickly take advantage of lambda expressions (closures), streams, and other Java language and platform improvements. Horstmann covers everything developers need to know about modern Java',
   2015),
  (13, 'Яков Файн', 'Программирование на Java для детей, родителей, дедушек и бабушек',
   'Это действительно первая книга по Java, которая создана именно для обучения детей. Яков Файн — автор и соавтор нескольких книг по Java, программист с многолетним опытом, так что не стоит думать, что книга написана новичком для новичков. Издание подойдет не только детям, но и преподавателям информатики, а также людям любого возраста, которые не имеют никакого представления о программировании.',
   2011),
  (14, 'Kishori Sharan', 'Learn JavaFX 8',
   'Learn JavaFX 8 shows you how to start developing rich-client desktop applications using your Java skills and provides comprehensive coverage of JavaFX 8’s features. Each chapter starts with an introduction to the topic at hand, followed by a step-by-step discussion of the topic with small snippets of code. The book contains numerous figures aiding readers in visualizing the GUI that is built at every step in the discussion.
The book starts with an introduction to JavaFX and its history. It lists the system requirements and the steps to start developing JavaFX applications. It shows you how to create a Hello World application in JavaFX, explaining every line of code in the process. Later in the book, author Kishori Sharan discusses advanced topics such as 2D and 3D graphics, charts, FXML, advanced controls, and printing. Some of the advanced controls such as TableView, TreeTableView and WebView are covered at length in separate chapters.
This book provides complete and comprehensive coverage of JavaFX 8 features; uses an incremental approach to teach JavaFX, assuming no prior GUI knowledge; includes code snippets, complete programs, and pictures; covers MVC patterns using JavaFX; and covers advanced topics such as FXML, effects, transformations, charts, images, canvas, audio and video, DnD, and more. So, after reading and using this book, you’ll come away with a comprehensive introduction to the JavaFX APIs as found in the new Java 8 platform.',
   2015),
  (15, 'Ильдар Хабибуллин', 'Java 7',
   'Рассмотрено все необходимое для разработки, компиляции, отладки и запуска приложений Java. Изложены практические приемы использования как традиционных, так и новейших конструкций объектно-ориентированного языка Java, графической библиотеки классов Swing, расширенной библиотеки Java 2D, работа со звуком, печать, способы русификации программ. Приведено полное описание нововведений Java SE 7: двоичная запись чисел, строковые варианты разветвлений, «ромбовидный оператор», NIO2, новые средства многопоточности и др. Дано подробное изложение последней версии сервлетов, технологии JSP и библиотек тегов JSTL. Около двухсот законченных программ иллюстрируют рассмотренные приемы программирования. Приведена подробная справочная информация о классах и методах Core Java API.',
   2012),
  (16, 'Scott Oaks', 'Java Performance: The Definitive Guide',
   'Coding and testing are often considered separate areas of expertise. In this comprehensive guide, author and Java expert Scott Oaks takes the approach that anyone who works with Java should be equally adept at understanding how code behaves in the JVM, as well as the tunings likely to help its performance.
You’ll gain in-depth knowledge of Java application performance, using the Java Virtual Machine (JVM) and the Java platform, including the language and API. Developers and performance engineers alike will learn a variety of features, tools, and processes for improving the way Java 7 and 8 applications perform.',
   2014),
  (17, 'Кларенс Хо, Роб Харроп',
   'Spring 3 для профессионалов',
   'Гибкая, облегченная, с открытым кодом платформа Spring Framework продолжает занимать место лидирующей инфраструктуры для разработки приложений на Java для современных программистов и разработчиков. Она работает в тесной интеграции с другими гибкими и облегченными Java-технологиями с открытым кодом, такими как Hibernate, Groovy, MyBatis и т.д. В настоящее время Spring также может взаимодействовать с Java EE и JPA 2. Эта книга посвящена новейшей версии платформы Spring Framework — версии 3.1. Широкий спектр рассматриваемых вопросов делает данную книгу наиболее полным руководством по Spring из числа доступных на рынке. Благодаря настоящей книге, вы изучите основы Spring, освоите ключевые темы, а также ознакомитесь с реальным опытом реализации в приложениях удаленной обработки, Hibernate и EJB. Помимо основ, вы узнаете, как использовать Spring Framework для построения различных уровней или частей корпоративного Java-приложения, в том числе транзакций, веб-уровня и уровня презентаций, развертывания и многого другого. Полнофункциональный пример приложения позволит применить на практике многие технологии и подходы, описанные в книге, и посмотреть, как они работают вместе. После чтения этой книги вы сможете оснастить арсенал своих знаний мощью Spring и задействовать его для построения сложных приложений Spring.',
   2012),
  (18, 'Joseph B. Ottinger, Dave Minter, Jeff Linwood', 'Beginning Hibernate, 3rd Edition',
   'Beginning Hibernate, Third Edition is ideal if you’re experienced in Java with databases (the traditional, or «connected,» approach), but new to open-source, lightweight Hibernate, a leading object-relational mapping and database-oriented application development framework.
This book packs in information about the release of the Hibernate 4.x persistence layer and provides a clear introduction to the current standard for object-relational persistence in Java. And since the book keeps its focus on Hibernate without wasting time on nonessential third-party tools, you’ll be able to immediately start building transaction-based engines and applications.
Experienced authors Joseph Ottinger with Dave Minter and Jeff Linwood provide more in-depth examples than any other book for Hibernate beginners. The authors also present material in a lively, example-based manner—not a dry, theoretical, hard-to-read fashion.',
   2014),
  (19, 'Роберт Лафоре', 'Структуры данных и алгоритмы в Java, 2-е издание',
   'Второе издание одной из самых авторитетных книг по программированию посвящено использованию структур данных и алгоритмов. Алгоритмы — это основа программирования, определяющая, каким образом разрабатываемое программное обеспечение будет использовать структуры данных. На четких и простых программных примерах автор объясняет эту сложную тему, предлагая читателям написать собственные программы и на практике освоить полученные знания. Рассматриваемые примеры написаны на языке Java, хотя для усвоения материала читателю не обязательно хорошо знать его — достаточно владеть любым языком программирования, например C++. Первая часть книги представляет собой введение в алгоритмизацию и структуры данных, а также содержит изложение основ объектно-ориентированного программирования. Следующие части посвящены различным алгоритмам и структурам данных, рассматриваемым от простого к сложному: сортировка, абстрактные типы данных, связанные списки, рекурсия, древовидные структуры данных, хеширование, пирамиды, графы. Приводятся рекомендации по использованию алгоритмов и выбору той или иной структуры данных в зависимости от поставленной задачи.',
   2013),
  (20, 'Дастин Босуэлл, Тревор Фаучер', 'Читаемый код, или Программирование как искусство', 'Любому программисту доводилось видеть код, который настолько неаккуратен и так пестрит ошибками, что от его чтения начинает болеть голова. За пять лет авторы этой книги проанализировали сотни примеров «плохого» кода (в основном — собственного), пытаясь определить, чем плох тот или иной код и как его можно улучшить. К какому выводу они пришли? Необходимо писать такой код, который читатель сможет понять максимально быстро, даже если этот читатель — сам создатель этого кода.
В данной книге рассматриваются базовые принципы и практические методы, которые можно применять при написании кода. В каждой главе на примере несложных образцов кода, написанного на разных языках программирования, изучается отдельный аспект создания кода и демонстрируется, как сделать код простым для понимания.',
   2012);